django-project/books/urls.py
from django.urls import re_path

from .views import (
	ContentListView, 
	ContentDetailView, 
	GenreListView, 
	BooksCreateView, 
	BooksManageView, 
	BooksDeleteView, 
	BooksUpdateView,
)

app_name = 'list'
app_name = 'detail'
app_name = 'add'

urlpatterns = [
	re_path('^manage/update/(?P<pk>\d+)$', BooksUpdateView.as_view(), name='update'),
	re_path('^manage/delete/(?P<pk>\d+)$', BooksDeleteView.as_view(), name='delete'),
	re_path('^manage/$', BooksManageView.as_view(), name='manage'),
	re_path('^add/$', BooksCreateView.as_view(), name='add'),
	re_path('^genre/(?P<genre>[\w-]+)/(?P<page>\d+)$', GenreListView.as_view(), name='genres'),
	re_path('^detail/(?P<slug>[\w-]+)$', ContentDetailView.as_view(), name='detail'),
	re_path('^(?P<page>\d+)$', ContentListView.as_view(), name='list'),    
]

django-project/website/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.views.generic import TemplateView


from .views import WebHomeView

urlpatterns = [
	re_path('^$', WebHomeView.as_view(template_name='index.html'), name='home'),
	path('books/', include('books.urls', namespace='books'), name='list'),
	path('admin/', admin.site.urls),
	
    
]

django-project/books/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse

# Create your models here.

class Books(models.Model):
	title	= models.CharField(max_length=255)
	content = models.TextField()
	genre	= models.CharField(max_length=255)
	author  = models.CharField(max_length=255)
	published = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	slug	= models.SlugField(blank=True, editable=False)

	def save(self):
		self.slug =	slugify(self.title)
		super().save()


	def get_absolute_url(self):
		url_slug = {'slug':self.slug}
		return reverse('books:detail', kwargs=url_slug)

	def __str__(self):
		return "{}. {}".format(self.id, self.title)

django-project/books/forms.py
from django.forms import ModelForm

from .models import Books

class BooksForm(ModelForm):
	class Meta:
		model = Books
		fields = [
			'title',
			'content',
			'genre',
			'author',
		]

django-project/books/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy

#load model
from .models import Books
from .forms import BooksForm


# Create your views here.

class BooksPerGenre():
	model = Books

	def get_latest_books_each_genre(self):
		genre_list = self.model.objects.values_list('genre', flat=True).distinct()
		queryset = []
		
		# untuk setiapgenre di dalam genre_list
		# maka setiap objek dalam genre akan di retrieve datanya sesuai genre
		# kemudian data yang diambil data paling baru sesuai dengan published
		# setelah itu menambah ke queryset dengan append
		for genre in genre_list:
			books = self.model.objects.filter(genre=genre).latest('published')
			queryset.append(books)
		return queryset

class BooksUpdateView(UpdateView):
	form_class = BooksForm
	model = Books
	template_name = "books/content_update.html"

class BooksDeleteView(DeleteView):
	model = Books
	template_name = "books/delete_confirmation.html"
	success_url = reverse_lazy('books:manage')

class BooksManageView(ListView):
	model = Books
	template_name = "books/content_manage.html"
	context_object_name = 'books_list'

class BooksCreateView(CreateView):
	form_class = BooksForm
	template_name = 'books/content_create.html'


class GenreListView(ListView):
	model 		  = Books
	template_name ="books/books_genre_list.html"
	context_object_name = 'books_list'
	ordering 	  = ['-published']
	paginate_by	  = 4

	def get_queryset(self):
		self.queryset = self.model.objects.filter(genre=self.kwargs['genre'])
		return super().get_queryset()

	def get_context_data(self, *args, **kwargs):
		genre_list = self.model.objects.values_list('genre', flat=True).distinct().exclude(genre=self.kwargs['genre'])
		self.kwargs.update({'genre_list':genre_list})
		kwargs = self.kwargs
		return super().get_context_data(*args, **kwargs)


class ContentListView(ListView):
	model 		  = Books
	template_name = "books/content_list.html"
	context_object_name = 'books_list'
	ordering 	  = ['-published']
	paginate_by   = 4

	def get_context_data(self, *args, **kwargs):
		genre_list = self.model.objects.values_list('genre', flat=True).distinct()
		self.kwargs.update({'genre_list':genre_list})
		kwargs = self.kwargs
		return super().get_context_data(*args, **kwargs)


class ContentDetailView(DetailView):
	model 		  = Books
	template_name = "books/content_detail.html"
	context_object_name = 'books'

django-project/website/views.py
from django.views.generic import TemplateView
from books.views import BooksPerGenre

class WebHomeView(TemplateView, BooksPerGenre):
	template_name = 'index.html'

	def get_context_data(self):
		queryset= self.get_latest_books_each_genre()
		context = {
			'latest_book_list':queryset,
		}

		return context

django-project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block page_title %}
			
		{% endblock page_title %}
	</title>
	{% include 'snippets/styles.html' %}
</head>
<body>
	{% include 'snippets/navbar.html' %}

	<div class="container" style="margin:100px">
		{% block book_contents %}


		{% endblock book_contents %}	
	</div>


	{% include 'snippets/scripts.html' %}	
</body>
</html>

django-project/templates/books/books_genre_list.html
{% extends "base.html" %}

{% block page_title %}
	Browse a Book
{% endblock page_title %}


{% block book_contents %}

<div class="row">
	<div class="col-md-8">
		<h2>Genre {{genre}}</h2>
		{% for books  in books_list  %}
			<h3>
				<a class="text-dark" href="{% url 'books:detail' books.slug %}"> {{books.title}} </a>
			</h3>
			<p> Author: {{books.author}} | Published by admin at {{books.published}} </p>
			<p align="justify">{{books.content | truncatewords:75}} 
				<a href="{% url 'books:detail' books.slug %}"> Read More </a>
			</p>
		{% endfor %}

		{% if is_paginated %}

		<nav aria-label="contentPage">
			<ul class="pagination">

				{% if page_obj.has_previous %}
				<li class="page-item">
					<a class="page-link" href="{% url 'books:genres' genre page_obj.previous_page_number %}">&laquo;</a>
				</li>
				{% else %}
				<li class="page-item disabled">
					<a class="page-link" href="#" tabindex="-1" aria-disabled="true">&laquo;</a>
				</li>
				{% endif %}


				{% for page in paginator.page_range %}
				{% if page is page_obj.number %}
				<li class="page-item active" aria-current="page">
					<span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
				</li>
				{% else %}
				<li class="page-item">
					<a class="page-link" href="{% url 'books:genres' genre page %}">{{page}}</a>
				</li>
				{% endif %}
				{% endfor %}


				{% if page_obj.has_next %}
				<li class="page-item">
					<a class="page-link" href="{% url 'books:genres' genre page_obj.next_page_number %}">&raquo;</a>
				</li>
				{% else %}
				<li class="page-item disabled">
					<a class="page-link" href="#" tabindex="-1" aria-disabled="true">&raquo;</a>
				</li>
				{% endif %}
			</ul>
		</nav>

		{% endif %}
	</div>
	<div class="col-sm">
		<h3> More Genre </h3>
		<ul class="list-group list-group-flush">
			<li class="list-group-item"> 
				<a href="{% url 'books:list' 1 %}"><b>all genres</b></a>
			</li>
			{% for genre in genre_list  %}
			<li class="list-group-item"> 
				<a href="{% url 'books:genres' genre 1%}">{{genre}}</a>
			</li>
			{% endfor %}
		</ul>
	</div>
</div>

{% endblock book_contents %}

django-project/templates/books/content_create.html
{% extends "base.html" %}

{% block page_title %}
	Add Literature
{% endblock page_title %}

{% block book_contents %}
	<h1>Add New Literature</h1>

	<form method='POST'>
		{% csrf_token %}
		<div class="form-group">
		    <label for="{{form.title.id_for_label}}">{{form.title.label}}:</label>
		    <input type="text" class="form-control" name="{{form.title.name}}" maxlength="{{form.title.max}}" required id="{{form.title.id_for_label}}" placeholder="Add title">    
		</div>

		<div class="form-group">
			<label for="{{form.content.id_for_label}}">{{form.content.label}}:</label>
			<textarea class="form-control" name="{{form.content.name}}" rows="10" required id="{{form.content.id_for_label}}" placeholder="Add the storyline"></textarea>
		</div>

		<div class="form-group">
		    <label for="{{form.genre.id_for_label}}">{{form.genre.label}}:</label>
		    <input type="text" class="form-control" name="{{form.genre.name}}" maxlength="{{form.genre.max}}" required id="{{form.genre.id_for_label}}" placeholder="Add genre">    
		</div>

		<div class="form-group">
		    <label for="{{form.author.id_for_label}}">{{form.author.label}}:</label>
		    <input type="text" class="form-control" name="{{form.author.name}}" maxlength="{{form.author.max}}" required id="{{form.author.id_for_label}}" placeholder="Add author">    
		</div>
		<button type="submit" class="btn btn-primary">Post</button>
	</form>
{% endblock book_contents %}

django-project/templates/books/content_detail.html
{% extends 'base.html' %}

{% block page_title %}
	{{books.title}}
{% endblock page_title %}

{% block book_contents %}
	<h1>{{books.title}}</h1>
	<h5>Genre: {{books.genre}} | Author: {{books.author}}</h5>
	<p align="justify">{{books.content}} </p>
	<p>Published by admin at {{books.published}}</p>
{% endblock book_contents %}

django-project/templates/books/content_list.html
{% extends "base.html" %}

{% block page_title %}
	Browse a Book
{% endblock page_title %}


{% block book_contents %}



<div class="row">
	<div class="col-md-8">
		{% if is_paginated %}

		<nav aria-label="contentPage">
			<ul class="pagination">

				{% if page_obj.has_previous %}
				<li class="page-item">
					<a class="page-link" href="{% url 'books:list' page_obj.previous_page_number %}">Previous</a>
				</li>
				{% else %}
				<li class="page-item disabled">
					<a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
				</li>
				{% endif %}


				{% for page in paginator.page_range %}
				{% if page is page_obj.number %}
				<li class="page-item active" aria-current="page">
					<span class="page-link" href="#">{{page}}<span class="sr-only">(current)</span></span>
				</li>
				{% else %}
				<li class="page-item">
					<a class="page-link" href="{% url 'books:list' page %}">{{page}}</a>
				</li>
				{% endif %}
				{% endfor %}


				{% if page_obj.has_next %}
				<li class="page-item">
					<a class="page-link" href="{% url 'books:list' page_obj.next_page_number %}">Next</a>
				</li>
				{% else %}
				<li class="page-item disabled">
					<a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
				</li>
				{% endif %}
			</ul>
		</nav>

		{% endif %}


		{% for books  in books_list  %}
			<h3>
				<a class="text-dark" href="{% url 'books:detail' books.slug %}">{{books.title}}</a>
			</h3>
			<p>Genre: {{books.genre}} | Author: {{books.author}}</p>
			<p align="justify">{{books.content | truncatewords:75}} 
				<a href="{% url 'books:detail' books.slug %}">Read More</a>
			</p>
		{% endfor %}
	</div>
	<div class="col-sm">
		<h3> Genre </h3>
		<ul class="list-group list-group-flush">
			{% for genre in genre_list  %}
			<li class="list-group-item">
				<a href="{% url 'books:genres' genre 1%}">{{genre}}</a>
			</li>
			{% endfor %}
		</ul>
	</div>
</div>



{% endblock book_contents %}

django-project/templates/books/content_manage.html
{% extends "base.html" %}

{% block page_title %}
	Manage Literature
{% endblock page_title %}

{% block book_contents %}
	<h1>Manage Literature</h1>
	<a type="button" class="btn btn-primary btn-block" href="{% url 'books:add' %}">Add New Literature</a>
	<table class="table mt-2">
		<thead class="thead-dark">
			<tr>
				<th scope="col">#</th>
				<th scope="col" width="300px">Title</th>
				<th scope="col">Genre</th>
				<th scope="col">Author</th>
				<th scope="col">Published</th>
				<th scope="col">Action</th>
			</tr>
		</thead>
		<tbody>
			{% for books in books_list %}
			<tr>
				<th scope="row">{{forloop.counter}}</th>
				<td>{{books.title}}</td>
				<td>{{books.genre}}</td>
				<td>{{books.author}}</td>
				<td>{{books.published|date}}</td>
				<td>
					<a class="btn btn-warning" href="{% url 'books:update' books.id %}">Edit</a>
					<a class="btn btn-danger" href="{% url 'books:delete' books.id %}">Delete</a>
				</td>
			</tr>				
			{% endfor %}

		</tbody>
	</table>

{% endblock book_contents %}

django-project/templates/books/content_update.html
{% extends "base.html" %}

{% block page_title %}
	Update Literature
{% endblock page_title %}

{% block book_contents %}
	<h1>Update Literature</h1>

	<form method='POST'>
		{% csrf_token %}
		<div class="form-group">
		    <label for="{{form.title.id_for_label}}">{{form.title.label}}:</label>
		    <input type="text" class="form-control" name="{{form.title.name}}" maxlength="{{form.title.max}}" required id="{{form.title.id_for_label}}" value="{{form.title.value}}">    
		</div>

		<div class="form-group">
			<label for="{{form.content.id_for_label}}">{{form.content.label}}:</label>
			<textarea class="form-control" name="{{form.content.name}}" rows="10" required id="{{form.content.id_for_label}}">{{form.content.value}}</textarea>
		</div>

		<div class="form-group">
		    <label for="{{form.genre.id_for_label}}">{{form.genre.label}}:</label>
		    <input type="text" class="form-control" name="{{form.genre.name}}" maxlength="{{form.genre.max}}" required id="{{form.genre.id_for_label}}" value="{{form.genre.value}}">    
		</div>

		<div class="form-group">
		    <label for="{{form.author.id_for_label}}">{{form.author.label}}:</label>
		    <input type="text" class="form-control" name="{{form.author.name}}" maxlength="{{form.author.max}}" required id="{{form.author.id_for_label}}" value="{{form.author.value}}">    
		</div>
		<button type="submit" class="btn btn-warning">Update</button>
		<a type="submit" class="btn btn-danger" href="{% url 'books:manage' %}">Cancel</A>
	</form>
{% endblock book_contents %}

django-project/templates/books/delete_confirmation.html
{% extends "base.html" %}

{% block page_title %}
	Manage Literature
{% endblock page_title %}

{% block book_contents %}
	<h1>Delete Literature</h1>
	<p>Are you sure to delete this literature?</p>
	<h3>{{books.title}}</h3>
	<p>{{books.published}}</p>
	<form method="POST">
		{% csrf_token %}
		<button type="submit" class="btn btn-outline-dark">Yes</button>
		<a class="btn btn-outline-danger" href="{% url 'books:manage' %}">No</a>
	</form>
{% endblock book_contents %}

django-project/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block page_title %}
		GhouLibrary
		{% endblock page_title %}
	</title>
	{% include 'snippets/styles.html' %}
</head>

<body>
	{% include 'snippets/navbar.html' %}
	
	<div class="container">	
		{% block book_contents %}

		<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
			<ol class="carousel-indicators">
				<li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
				<li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
				<li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner">
				<div class="carousel-item active">
					<img src="https://i.ibb.co/qrPWXYp/pic10.jpg" class="d-block w-100" alt="...">
					<div class="carousel-caption d-none d-md-block">
						<h5>Welcome to GhouLibrary</h5>
						<p>You can read anything you want. Enjoy here!</p>
					</div>
				</div>
				<div class="carousel-item">
					<img src="https://i.ibb.co/vL9rZXT/pic12.jpg" class="d-block w-100" alt="...">
					<div class="carousel-caption d-none d-md-block">
						<h5>“Books are the ultimate Dumpees: put them down and they’ll wait for you forever; pay attention to them and they always love you back.”</h5>
						<p>― John Green, An Abundance of Katherines</p>
					</div>
				</div>
				<div class="carousel-item">
					<img src="https://i.ibb.co/n3XGwQf/pic11.jpg" class="d-block w-100" alt="...">
					<div class="carousel-caption d-none d-md-block">
						<h5>“Books are a uniquely portable magic.”</h5>
						<p>― Stephen King, On Writing: A Memoir of the Craft</p>
					</div>
				</div>
			</div>
			<a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
				<span class="carousel-control-prev-icon" aria-hidden="true"></span>
				<span class="sr-only">Previous</span>
			</a>
			<a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
				<span class="carousel-control-next-icon" aria-hidden="true"></span>
				<span class="sr-only">Next</span>
			</a>
		</div>
		<div class="row">
			{% for books in latest_book_list %}
			<div class="col-sm-4 mt-4">
				<div class="card" >
					<img class="card-img-top" src="https://data.whicdn.com/images/332753862/original.jpg" alt="Card image cap">
					<div class="card-body">
						<h5 class="card-title"><a class="text-dark" href="{% url 'books:genres' books.genre 1 %}">{{books.genre}}</h5></a>
						<h6 class="card-subtitle mb-2 text-secondary">{{books.title}}</h5>
						<h6 class="card-subtitle mb-2 text-secondary">{{books.published}}</h5>
						<p class="card-text">{{books.content|truncatewords:10}}</p>
						</div>
						<div class="card-body">
							<a href="{% url 'books:detail' books.slug %}" class="card-link">Read More</a>
						</div>
					</div>
				</div>			
				{% endfor %}
			</div>


			{% endblock book_contents %}	
		</div>
		{% include 'snippets/scripts.html' %}	
</body>
</html>

django-project/templates/snippets/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark">
	<div class="container">
		<a class="navbar-brand" href="{% url 'home' %}">GhouLibrary</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarNavDropdown">
			<ul class="navbar-nav">
				<li class="nav-item active">
					<a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'books:list' 1 %}">Browse Literature</a>
				</li>
				<div class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						Activity
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
						<a class="dropdown-item" href="{% url 'books:add'%}">Add New Literature</a>
						<a class="dropdown-item" href="{% url 'books:manage'%}">Manage Literature</a>
					</div>
				</div>
			</ul>
		</div>
	</div>
</nav>

django-project/templates/snippets/scripts.html
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

django-project/templates/snippets/styles.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.css'%}">